### ISSUE TITLE
Host through nuget

### ISSUE THREAD

**Issue by dbasilio** [Xignite/DotNetSDK#2]
Can we get the sdk publically hosted through nuget? Way easier to manage updates and references that way.

**Comment by znwang** [comment]
Thanks for the feedback!  Creating a nuget package for the .NET SDK is currently on our list of to-do's, but currently haven't gotten to it yet.  I will keep this issue open until this is done.

**Comment by saarea** [comment]
+1

**Comment by buybackoff** [comment]
+1 for NuGet. Also, given that your dll is not obfuscated and everything is visible via free version of dotPeek, why you just don't publish the source? Unit tests for API calls could be more useful than docs.

**Comment by znwang** [comment]
@buybackoff 

Thank you for your feedback!

We haven't published the source code up until now because an SDK generator is responsible for creating both the Java and C# code in an automated fashion.  Any changes to the C# SDK source code directly will just be overwritten by the generator.  This is convenient for us because the SDKs are very closely coupled to our APIs.

There are over 800 c# class files generated which are mostly just filled in with some boiler plate code and lots of documentation.  We feel that this documentation is very important to our customers because it gives context to our APIs.  For example, what an InstrumentIdentifierBrief object is and what kind of data points it contains via intellisense or javadocs.

That being said, we would be more than happy to publish the source code to GitHub and will do so in a future release.

**Comment by znwang** [comment]
This has been published to nuget @ https://www.nuget.org/packages/Xignite.Sdk/.  The github page has also been updated to reflect this.
