### ISSUE TITLE
Increase MaxJsonLength parameter when calling the JSON serializer

### ISSUE THREAD

**Issue by mattmamou** [Xignite/DotNetSDK#3]
We can't currently pull the full quote history for a single stock.
Thanks,
Mathias

**Comment by xignite-engineering** [comment]
What version of the SDK are you using?

On Wednesday, September 23, 2015, mattmamou notifications@github.com
wrote:

> We can't currently pull the full quote history for a single stock.
> Thanks,
> Mathias
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Xignite/DotNetSDK/issues/3.

## 

_::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::__Z
Wang_
Software Engineer

_Xignite Inc._ On-Demand Financial Market Data
1.866.XML.SOAP (1.866.965.7627)
Office: 1.650.242.4248
Fax: 1.650.655.3703

Web http://www.xignite.com/  Facebook
http://www.facebook.com/#%21/pages/Xignite/115738573535?ref=search&sid=689098967.2893475143..1
Twitter http://twitter.com/xignite
_::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::_

**Comment by mattmamou** [comment]
My version is 0.2.4.0

**Comment by xignite-engineering** [comment]
Thanks.  You are using a beta version.  This issue has been fixed with one
of the production versions.  You can get the latest version here:
https://github.com/Xignite/DotNetSDK/releases.

Please also take a look at the release history for more information.

Btw, this is also available as a nuget package:

https://www.nuget.org/packages/Xignite.Sdk/

On Wednesday, September 23, 2015, mattmamou notifications@github.com
wrote:

> My version is 0.2.4.0
> 
> On Wed, Sep 23, 2015 at 4:15 PM xignite-engineering <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > What version of the SDK are you using?
> > 
> > On Wednesday, September 23, 2015, mattmamou <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > We can't currently pull the full quote history for a single stock.
> > > Thanks,
> > > Mathias
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/Xignite/DotNetSDK/issues/3.
> > 
> > ## 
> > 
> > _::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::__Z
> > Wang_
> > Software Engineer
> > 
> > _Xignite Inc._ On-Demand Financial Market Data
> > 1.866.XML.SOAP (1.866.965.7627)
> > Office: 1.650.242.4248
> > Fax: 1.650.655.3703
> > 
> > Web http://www.xignite.com/ Facebook
> > <
> > 
> > http://www.facebook.com/#%21/pages/Xignite/115738573535?ref=search&sid=689098967.2893475143..1
> > 
> > > Twitter http://twitter.com/xignite
> > 
> > _::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::_
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Xignite/DotNetSDK/issues/3#issuecomment-142636150.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Xignite/DotNetSDK/issues/3#issuecomment-142637211.

## 

_::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::__Z
Wang_
Software Engineer

_Xignite Inc._ On-Demand Financial Market Data
1.866.XML.SOAP (1.866.965.7627)
Office: 1.650.242.4248
Fax: 1.650.655.3703

Web http://www.xignite.com/  Facebook
http://www.facebook.com/#%21/pages/Xignite/115738573535?ref=search&sid=689098967.2893475143..1
Twitter http://twitter.com/xignite
_::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::_

**Comment by mattmamou** [comment]
Cool thanks
